In [2]:
import pandas as pd
import cv2
# from helpers import get_folder_summary

In [4]:
df = pd.read_csv(r'C:\Users\aleks\OneDrive\Documents\inzynierka\wyniki_gridsearch.csv')
df

,architecture,lr,batch_size,epochs,mean_accuracy,std_accuracy,mean_f1,std_f1
0,resnet18,0.0010,16,20,87.762478,4.281390,0.792326,0.077431
1,resnet18,0.0010,32,20,90.169248,3.516106,0.823624,0.093170
2,resnet18,0.0001,16,20,93.032129,3.098935,0.876726,0.066062
3,resnet18,0.0001,32,20,91.838784,2.230302,0.848977,0.052843
4,vgg16,0.0010,16,20,91.368330,1.393699,0.838574,0.030689
5,vgg16,0.0010,32,20,90.172117,2.965010,0.822619,0.053519
6,vgg16,0.0001,16,20,91.606426,2.152618,0.846790,0.043074
7,vgg16,0.0001,32,20,91.127367,2.994067,0.839989,0.052899
8,custom_cnn,0.0010,16,20,72.403901,3.361647,0.638210,0.016194
9,custom_cnn,0.0010,32,20,80.321285,7.007228,0.741293,0.084138
10,custom_cnn,0.0001,16,20,86.336776,2.874715,0.766189,0.077577
11,custom_cnn,0.0001,32,20,86.572002,2.955043,0.787053,0.053511

In [1]:
from helpers import get_folder_summary


data_path = r'C:\Users\aleks\OneDrive\Documents\inzynierka\data\data_single'
df = get_folder_summary(data_path)
df

,Folder,Liczba plików,Minimalna szerokość,Minimalna wysokość,Maksymalna szerokość,Maksymalna wysokość
0,HSIL,124,1130,1129,1130,1130
1,LSIL,60,1130,986,1130,1130
2,NSIL,233,1130,958,2510,1540

In [2]:
data_path = r'C:\Users\aleks\OneDrive\Documents\inzynierka\data\LBC_slides'
df = get_folder_summary(data_path)
df

,Folder,Liczba plików,Minimalna szerokość,Minimalna wysokość,Maksymalna szerokość,Maksymalna wysokość
0,HSILpow 10,62,2510,1540,2510,1540
1,HSILpow 40,62,2510,1479,2510,1540
2,LSILkoilocyty/pow 10,29,2418,1540,2510,1540
3,LSILkoilocyty/pow 40,32,2510,1540,2540,1540
4,LSILpow 40,35,2510,1540,2510,1540
5,LSILpow. 10,30,2510,1540,2510,1540
6,NSILpow 40,157,1540,1540,2510,2510
7,NSILpow. 10,76,1540,1540,2510,2510

In [3]:
data_path = r'C:\Users\aleks\OneDrive\Documents\inzynierka\data\data_mendeley'
df = get_folder_summary(data_path)
df

,Folder,Liczba plików,Minimalna szerokość,Minimalna wysokość,Maksymalna szerokość,Maksymalna wysokość
0,High squamous intra-epithelial lesion,163,2048,1536,2048,1536
1,Low squamous intra-epithelial lesion,113,2048,1536,2048,1536
2,Negative for Intraepithelial malignancy,612,2048,1536,2048,1536

In [5]:
data_path = r'C:\Users\aleks\OneDrive\Documents\inzynierka\data_yolo'
df = get_folder_summary(data_path)
df

,Folder,Liczba plików,Minimalna szerokość,Minimalna wysokość,Maksymalna szerokość,Maksymalna wysokość
0,data_mine_labelstrain_data/images,66,2510.0,1540.0,2510.0,1540.0
1,data_mine_labelstrain_data/labels,0,NaN,NaN,NaN,NaN
2,data_mine_labelsval/images,6,2510.0,1540.0,2510.0,1540.0
3,data_mine_labelsval/labels,0,NaN,NaN,NaN,NaN
4,data_synteticimages,250,1024.0,1024.0,1024.0,1024.0
5,data_synteticlabels,0,NaN,NaN,NaN,NaN
6,syntetic_and_mineimages,170,1024.0,1024.0,2510.0,1540.0
7,syntetic_and_minelabels,0,NaN,NaN,NaN,NaN
8,syntetic_and_mine_valimages,29,1024.0,1024.0,2510.0,1540.0
9,syntetic_and_mine_vallabels,0,NaN,NaN,NaN,NaN
10,testtest_hybrid/HSIL,16,2510.0,1540.0,2510.0,1540.0
11,testtest_hybrid/LSIL,16,2510.0,1540.0,2510.0,1540.0
12,testtest_hybrid_23/HSIL,16,2510.0,1540.0,2510.0,1540.0
13,testtest_hybrid_23/HSIL-mendeley,16,2048.0,1536.0,2048.0,1536.0
14,testtest_hybrid_23/LSIL,16,2510.0,1540.0,2510.0,1540.0
15,testtest_hybrid_23/LSIL-mendeley,16,2048.0,1536.0,2048.0,1536.0
16,testtest_hybrid_23/NSIL,16,2510.0,1540.0,2510.0,1540.0
17,testtest_hybrid_23/NSIL-mendeley,16,2048.0,1536.0,2048.0,1536.0
18,testtest_nowy_mine_labels/HSIL,62,2510.0,1540.0,2510.0,1540.0
19,testtest_nowy_mine_labels/LSIL,77,1540.0,1540.0,2510.0,2510.0
20,testtest_nowy_mine_labels/MENDELEYHSil,16,2048.0,1536.0,2048.0,1536.0
21,testtest_nowy_mine_labels/MENDELEYlsil,16,2048.0,1536.0,2048.0,1536.0
22,testtest_nowy_mine_labels/MENDELEYnsil,509,2048.0,1536.0,2048.0,1536.0
23,testtest_nowy_mine_labels/NSIL,76,1540.0,1540.0,2510.0,2510.0
24,testtest_nowy_mine_labels/val,6,2510.0,1540.0,2510.0,1540.0
25,testtest_results2,76,1540.0,1540.0,2510.0,2510.0